name = "MFGnet"
uuid = "97b447e0-6553-5d69-bee2-d3681083803f"
license = "MIT"
desc = "A Machine Learning Framework for solving Mean Field Games and Control Problems"
authors = ["Lars Ruthotto <lruthotto@emory.edu>", "Samy Wu Fung <swufung@math.ucla.edu>"]
version = "0.0.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Zygote ="e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1.2"
